### ISSUE TITLE
Một số sửa đổi trong việc thiết kế cơ sở dữ liệu

### ISSUE THREAD

**Issue by duongvu5** [PTIT-D22KH/milktea_sales_management_project#4]
* Bỏ bớt cái thuộc tính birthDay của customer , thêm thuộc tính rebate tức là tiền trả lại vào trong bảng Order
* Xoá 2 thuộc tính shipperName với shipperPhoneNumber và thêm thuộc tính customerId cho bảng shipment , tức là cho nhân viên ship luôn
* Xoá notice ở trong bảng shipper do k hiểu nó làm gì
* Đổi urlImage thành imagePath ở trong bảng food item
* Các thuộc tính id của các bảng thì viết thêm cái tên bảng vào trước cái id cho rõ, ví dụ bảng customer thì là customerId
* Và có thể thêm 1 số thứ khác, nếu như ghi thiếu, có thể bổ sung sau

**Comment by duongvu5** [comment]
@PTIT-D22KH/btn_java_24-25t1_nmson

**Comment by duongvu5** [comment]
https://github.com/PTIT-D22KH/test_repo_template/blob/main/restaurant-manager-mvc-swing-1.3/src/main/resources/database/new_table.sql

**Comment by TINABJan254** [comment]
trong file 

> https://github.com/PTIT-D22KH/test_repo_template/blob/main/restaurant-manager-mvc-swing-1.3/src/main/resources/database/new_table.sql

trong new_database.sql, bảng employee thiếu trường salary

**Comment by duongvu5** [comment]
> > https://github.com/PTIT-D22KH/test_repo_template/blob/main/restaurant-manager-mvc-swing-1.3/src/main/resources/database/new_table.sql
> 
> trong file new_database.sql, bảng employee thiếu trường salary

đã sửa!

**Comment by duongvu5** [comment]
Có sai sót trong file `create_new_table.sql` . Bảng `shipment` thiếu trường `shipCost`
